### PR TITLE
Added support for Linux arm64

### PR DESCRIPTION
**Pull request by xemle**
Here is my PR for linux-arm64 as result from the [discussions](https://github.com/getgauge/gauge/discussions/2035).

### CODE REVIEW

**Review by sriv — DISMISSED** [review]

**Comment by xemle** [comment]
Hi. Thank you for the release candidate. I increased the minor level since it is a new feature and not a bug. If it is not appropriate, please leave a message and I will change it.

**Review by sriv — APPROVED** [review]

**Comment by xemle** [comment]
Just want to say thank you for merging and releasing arm64 feature. Gauge works nicely on my Raspberry PI 4 with Ubuntu 21.04

**Comment by sriv** [comment]
Glad everything works @xemle - please feel free to post back with any feedback on this.

**Comment by xemle** [comment]
A success story feedback:

I've just integrated gauge in my [gitea](https://gitea.io) + [drone.io](https://www.drone.io) CI on a Raspberry Pi 4 at home for my pet project [HomeGallery](https://home-gallery.org) - a self hosted web photo gallery. See [CI definition](https://github.com/xemle/home-gallery/blob/master/.drone.yml#L30) and my [e2e tests](https://github.com/xemle/home-gallery/tree/master/e2e) using gauge.js and html-report on arm64.

image

Just awesome. Thank you so much - now I can sleep better ;-)

**Pull request merged**
