### PR TITLE
Update for providing concept starting and ending to reporter

### PR DESCRIPTION
**Pull request by jensakejohansson**
Solution proposal for issue:
https://github.com/getgauge/gauge/issues/2450

Added functionality to send start & end concept related messages to plugins.

Related PR in gauge-proto repo is created:

https://github.com/getgauge/gauge-proto/pull/30

### CODE REVIEW

**Comment by jensakejohansson** [comment]
@sriv Can you please check this PR too. It's related to the other one you accepted a couple of day ago (https://github.com/getgauge/gauge-proto/pull/30). 

I think the checks failed because when they were executed the needed gauge-proto updates were not yet merged. I don't see how to re-run the checks now when the gauge-proto PR is merged. Can you please assist?

**Comment by sriv** [comment]
Will do in a few hours time (after work). I tried re-triggering, but it failed. I guess the submodule needs to be updated and protos need to be regenerated in gauge repo.

**Comment by sriv** [comment]
I had a look, so this pull request needs to include updates to the proto changes. i.e. you need to run

`go get -u github.com/getgauge/gauge-proto/go/gauge_messages`  to include the concept starting and ending messages. this should change the go.mod and go.sum files.

I tried this on my local and `go test ./...` passed for me. But it wont let me push the changes to this PR. Could you please try updating the deps and check? the workflows should retrigger.

golangci-lint seems to be unhappy with similar reason, so we can check that post these changes.

**Comment by PiotrNestor** [comment]
OK. According to your suggestions:

$ git status
On branch reporter-concept-update

1. $ go get -u github.com/getgauge/gauge-proto/go/gauge_messages
go: downloading github.com/getgauge/gauge-proto/go/gauge_messages v0.0.0-20240117152029-6ad2c75d5dea
go: module github.com/golang/protobuf is deprecated: Use the "google.golang.org/protobuf" module instead.

2. Checked that all tests work OK
3. git add --all
 git commit -s -m "Update go.mod and go.sum files"
 git push

**Comment by sriv** [comment]
https://github.com/getgauge/gauge/pull/2451/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R3

I guess the go version changed to 1.21.5 when you did the dep update and both golangci-lint and codeql jobs fail because of that. Even the netlify build fails stating the same error - https://app.netlify.com/sites/stupefied-euclid-38c3ac/deploys/65aa72222ab68800082b868c#L66

**Comment by PiotrNestor** [comment]
@sriv
What is the next step then?

**Comment by sriv** [comment]
@PiotrNestor try reverting thego version to 1.21?

**Comment by PiotrNestor** [comment]
@sriv
Pushed go.mod update to revert to go 1.21

**Comment by PiotrNestor** [comment]
@sriv
The 'html-report' plugin needs an update now in order to complete the FT steps??
This is a strange chain of dependencies ...
Also there are problems to build the 'html-report' plugin because of problems with github.com/getgauge/mflag.test

**Comment by sriv** [comment]
Yes, that is strange. I don't believe that any additions to gauge's contract should impact the plugins.

I will look at html-report today, but I am curious if this impacts other report plugins as well. Will look into it today

**Comment by PiotrNestor** [comment]
@sriv
Regarding the 'html-report' plugin you can have a look at: https://github.com/system-verification/html-report/tree/reporter-concept-update.

I have updated the plugin with the following:
1. Added a local 'mflag' package that contains the files from 'https://github.com/getgauge/mflag' with some minor dependency fixes. This because 'github.com/docker/docker/pkg/mflag' is not available anymore
2. Updated gauge_messages
3. Updated handler.go. It still needs 'missing method mustEmbedUnimplementedReporterServer'

Obviously you can update  the 'html-report' plugin in your way. I think it requires much more work ...

**Comment by jensakejohansson** [comment]
@sriv 
Thanks for quick and good support! Next question: If we're going to ask Report Portal to try the new feature & update their plugin accordingly we need to make a release. Is that possible to do?

**Comment by chadlwilson** [comment]
Hey folks, I'm inferring this is not backward compatible with plugins? See https://github.com/getgauge/gauge/issues/2456 and https://github.com/getgauge/xml-report/issues/61

Seems a bit unexpected for a patch release?

**Comment by sriv** [comment]
yeah, it isn't backward compatible because of some updates to the proto generated code. It should be compatible from now on since the proto tooling has made some enhancements.

And my bad on the version bump - I have created 1.6.0 release, and will take down 1.5.7.

btw - I will also be making changes to xml-report and json-report soon.

**Comment by jensakejohansson** [comment]
Thanks @sriv for fixing. Sorry for causing disruptions with our update/PR. We learn as we go....

**Comment by PiotrNestor** [comment]
@sriv

A new PR regarding this issue: https://github.com/getgauge/gauge/pull/2461
ConceptEnd must also be sent when a concept step fails

**Comment by sriv** [comment]
The new PR is merged and gauge 1.6.1 is now released. Thanks @PiotrNestor

**Pull request merged**
