### PR TITLE
[WIP] Add multiline parameter capacity

### PR DESCRIPTION
**Pull request by FaustXVI**
First try to have multiline paramter (see #175).
**This is defintly not the final version** but I'd like to have your feedback.

TODOs 
- [ ] Quotes in mulitline should not have to be escaped
- [ ] For now, quotes needs to be on the first line. Starting it on a new line would be great
- [ ] I used two quotes instead of triple. I do think triple are nicer but it was simpler to do with double.
- [ ] tests in more a real case
- [ ] clean up some code :D

### CODE REVIEW

**Comment by sriv** [comment]
@FaustXVI - Thanks for getting this in motion. Quick question - I notice that the syntax for multiline arguments require two quotes? i.e. something like this:

```
* this is a step with ""multiline
  arguments""
```

Instead, it would be good if we can not overload parameter definition and use single double quotes, something like:

```
* this is a step with "multiline
  arguments"
```

Note that we might have to honour the indentations. There is a separate issue to support multiline step texts (#265). From [Markdown Specs](http://spec.commonmark.org/0.25/#list-items):

> If a sequence of lines Ls constitutes a list item according to rule #1, #2, or #3, then the result of indenting each line of Ls by 1-3 spaces (the same for each line) also constitutes a list item with the same contents and attributes. If a line is empty, then it need not be indented.

Example: http://spec.commonmark.org/0.25/#example-245

PS - I see that you had also [raised this](https://github.com/getgauge/gauge/issues/175#issuecomment-205003941) in #175. Apologies for not responding earlier.

**Comment by sriv** [comment]
Some thoughts on your TODOs:

> Quotes in mulitline should not have to be escaped

Actually, quotes on regular static parameters are supposed to be escaped, it would be good to keep this consistent on multiline parameters as well.

Note that there is another open issue (#172) that seeks to allow alternative quotes support. That would allow users to not have to escape quotes.

> For now, quotes needs to be on the first line. Starting it on a new line would be great

Actually, I like it being continuous. When we implement #265, parameter starting on new line could be just a special case of multiline step text. What do you say?

**Comment by FaustXVI** [comment]
@sriv thanks for the feedback.
Actually, I think that fixing #265 will give us multiline arguments for free and so, indeed, a single " would be nicer. I think I'll switch my focus to #265.
I do agree with #172 too since it totally solve the use case I have in mind. I'll add a comment to it.
Maybe the #175 could be marked as a kind of duplicate of #265 and #172 ?

**Comment by sriv** [comment]
@FaustXVI  - cool! Have you made any progress on #265 ? We were looking at #95 and it seems to be related as well.

If you haven't made any significant changes, I would like to address #95, since there are other dependant issues on #95 (ex. #290 ).

**Comment by FaustXVI** [comment]
@sriv I haven't done any significant work. Please go ahead with #95. I'll start to work on #265 in two weeks after my holydays.

**Comment by mahendrakariya** [comment]
@FaustXVI The changes in this PR has diverged a lot from the master branch. I am closing it for now.

**Comment by flyerfish** [comment]
has gauge multiline parameter capacity? how to write multiline parameter of step? thanks.

**Comment by apoorvam** [comment]
@flyerfish Currently, Gauge does not have multi-line step text/parameter support. [Here](https://github.com/getgauge/gauge/issues/175) is an open issue for multi-line argument support. You can add your comments/use case in this issue.

Gauge allows only table parameter to be present in line after step text. Example [here](https://github.com/getgauge/gauge-example-java/blob/ed0e38e0f9a22f28239da69e618a37af22204ab8/specs/products.spec).

**Pull request closed without merging**
