### PR TITLE
add substitution of env vars from property files #1679 and #1428

### PR DESCRIPTION
**Pull request by opursail**
If a property can't be substituted from system properties then the ones loaded from properties files are checked

### CODE REVIEW

**Comment by sriv** [comment]
thanks for the patch @opursail . I was testing this out, and most of the cases work. I did notice a case where nested access of properties does not work. For ex;

`env/default/default.properties` contains:

```
foo=bar
anotherFoo=${foo}/another
nestedFoo=${anotherFoo}/nested
secondNested=${nestedFoo}/2ndnested
```

resolves to

```
foo: bar
anotherFoo: bar/another
nestedFoo: ${foo}/another/nested
secondNested: ${foo}/another/nested/2ndnested
```

**Comment by opursail** [comment]
> thanks for the patch @opursail . I was testing this out, and most of the cases work. I did notice a case where nested access of properties does not work. For ex;
> 
> `env/default/default.properties` contains:
> 
> ```
> foo=bar
> anotherFoo=${foo}/another
> nestedFoo=${anotherFoo}/nested
> secondNested=${nestedFoo}/2ndnested
> ```
> 
> resolves to
> 
> ```
> foo: bar
> anotherFoo: bar/another
> nestedFoo: ${foo}/another/nested
> secondNested: ${foo}/another/nested/2ndnested
> ```
> 
> So, it looks like we need to figure out a way to allow nested substitution. And this could also lead to handling cyclic references.

@sriv 
I've already got a function to fix nested that deals with cyclic references. But it currently isn't very elegent. So I just went for a simple solution 

Do you want it to deal with nested properties as well?

**Comment by sriv** [comment]
@opursail - I think if this feature is brought in, there will be use cases around nested properties. Unless it is a significantly huge effort, I'd like to address it as well.

What do you say?

> I've already got a function to fix nested that deals with cyclic references. But it currently isn't very elegent.

I think that is ok, we can work on improving it if needed. Nothing is perfect to begin with.

**Comment by opursail** [comment]
Added commit to deal with nested env vars and protect against cyclic references.

**Comment by sriv** [comment]
thanks for the update @opursail, appreciate the effort.

I believe we should be able to report circular dependency a bit better (i.e point out which dependency tree becomes a cyclic graph). 

We [do this for concepts](https://github.com/getgauge/gauge/blob/35a13be9335c919f6eefdcb15ba6688846044de2/parser/conceptParser.go#L326-L365) 

If I extend the logic to properties, I'd imagine something like:

- create a dependency tree of properties.
      - the representation could be a tree structure, (or)
          - create a map of - `prop -> [immediate dependency]`
          - walk the map 
              - if `prop` is found in dependencies, we have a cyclic reference
              - exit when there dependencies are empyy array (i.e we've reached properties with 'pure' values)

This will enable better error reporting - i.e. ideally we'd like gauge to tell the users which properties cause cyclic dependencies, otherwise it could become a nightmare to sort this out!

I know that this is a considerable change, but I think it's best for our users. What do you feel?

**Comment by opursail** [comment]
Added commit to improve detecting and reporting circular dependency as suggested by @sriv

**Comment by sriv** [comment]
Thank you very much for this contribution @opursail. Much appreciated.

I think some of your commits need to be signed - please see https://github.com/getgauge/gauge/pull/1680/checks?check_run_id=884663594

Windows FT has failed, but it seems due to environmental reasons, so I've retriggered. Let's see.

**Comment by sriv** [comment]
@opursail did you mean to close this PR?

**Comment by opursail** [comment]
@sriv - needed to sort out my github signoff config, so have closed this one and re-raised as https://github.com/getgauge/gauge/pull/1700

**Pull request closed without merging**
