### PR TITLE
Updating the markdown for the URL to gauge-tests

### PR DESCRIPTION
**Pull request by moijes12**
Updating the markdown for the URL to gauge-tests

### CODE REVIEW

**Comment by moijes12** [comment]
As per the CLA, Thoughtworks will only be allowed to access to my contributions to gauge, would it not ?

**Comment by zabil** [comment]
@moijes12 thanks for your pull request

> As per the CLA, Thoughtworks will only be allowed to access to my contributions to gauge, would it not ?

Yes, this CLA is only for your contributions to Gauge.

**Comment by gaugeci** [comment]
@cla-bot check if all the contributors of this pull request has signed our CLA.

**Comment by Apoorva-GA** [comment]
@moijes12 thanks for the fix.

**Pull request merged**
