### PR TITLE
Add support notice section

### PR DESCRIPTION
**Pull request by zabil**
Add status of the project to that users and contributors are aware.

Related to: https://github.com/getgauge/gauge/issues/1732

### CODE REVIEW

**Comment by zabil** [comment]
@sriv added a notice to clearly mark Gauge's status. Please do take a look when you have the time.

**Comment by sriv** [comment]
Sounds good, I wonder if this can be an opportunity to call for maintainers. I remember @haroon-sheikh being interested (apologies, I totally forgot about it till now)

**Comment by haroon-sheikh** [comment]
Yep I'm happy to help out where possible.

**Comment by zabil** [comment]
@haroon-sheikh, added you to the core team. We appreciate your assistance. We understand that you have a day job, just like the rest of us, so we don't expect you to put in any additional effort beyond what you're already contributing. Once again, thank you for your help.

**Comment by haroon-sheikh** [comment]
@zabil can you add me to `getgauge-contrib` org as well please?

**Comment by haroon-sheikh** [comment]
> @zabil can you add me to `getgauge-contrib` org as well please? 

With write access please, I'm looking to merge an updates pr to getgauge-contrib/gauge-go and maven plugin. Thanks.

**Comment by zabil** [comment]
> With write access please, 

@haroon-sheikh can you check now?

**Pull request merged**
