### PR TITLE
Don't print a trailing space on steps with table args

### LINKED ISSUE #1787: Formatter adds trailing whitespace to steps that have table data
### Describe the bug

With the gauge spec formatter enabled in vscode, trailing whitespace is added to the end of my steps that have table input. E.g., this:

```diff
* Then something happens
- * Then something happens with this data
+ * Then something happens with this data 

   |foo|
   |---|
```

From experimenting with different formatter options and turning on and off the settings in vscode for trimming whitespace, I'm pretty sure that it's the gauge extension that's doing this.

### What command(s) did you run when you found the bug?

Just saving  / formatting a file in vscode

### Output, stack trace or logs related to the bug 

N/A

#### Gauge (Output of `gauge -v`)
```
Gauge version: 1.0.6
Commit Hash: 2bc49ddb

Plugins
-------
html-report (4.0.8)
screenshot (0.0.1)
ts (0.0.2)
```

#### Node.js/Java/Python/.Net/Ruby version

Node.js 12.13.1

#### Operating System information

macOS 10.14.6

#### IDE information

- VSCode: 1.49.2
- Gauge extension: 0.0.17

Edit: It only happens on lines with table data.

### PR DESCRIPTION
**Pull request by camjackson**
Fixes #1787 🙂

### CODE REVIEW

**Comment by camjackson** [comment]
Not sure what those failures about, from the logs it doesn't look like any tests or linter rules are actually failing?

**Comment by sriv** [comment]
@camjackson - I will take a look at this PR.

I am currently looking at a fix for #318 and I want to wrap that before I look at this, I assume there could be some overlap.

**Review by sriv — APPROVED** [review]

**Comment by camjackson** [comment]
Thanks for approving and merging, @sriv and @zabil! When can we expect to see a new version of the extension published with this change?

**Comment by sriv** [comment]
Hey @camjackson - gauge 1.1.6 is out and it includes this change -https://github.com/getgauge/gauge/releases/tag/v1.1.6

Thanks again for the contrib!

**Pull request merged**
