### PR TITLE
Build with go 1.21 and minor dependency bumps

### PR DESCRIPTION
**Pull request by chadlwilson**
Bumps golang to 1.21 along with a few dependency updates missed somehow.

### CODE REVIEW

**Review by haroon-sheikh — APPROVED** [review]

**Comment by chadlwilson** [comment]
I see other distinct PRs exist for some of the dependencies here. Let’s merge those and I’ll rebase this.

**Comment by haroon-sheikh** [comment]
@chadlwilson All of those are in now. Dont forget to update the gauge version for release ;)

**Comment by chadlwilson** [comment]
Done now, build is running - thanks @haroon-sheikh !

**Comment by haroon-sheikh** [comment]
One of the FT is really flaky on windows, I need to find some time to investigate.

**Comment by chadlwilson** [comment]
Yeah, Ive noted that elsewhere myself, haven't had time to investigate either.

**Comment by chadlwilson** [comment]
@haroon-sheikh think this one needs your mind re-review :-)

**Review by haroon-sheikh — APPROVED** [review]

**Pull request merged**
