### PR TITLE
add support to print list of implemented steps

### LINKED ISSUE #2432: Get list of steps via `gauge list`
### Discussed in https://github.com/getgauge/gauge/discussions/2423

<div type='discussions-op-text'>

<sup>Originally posted by **EGTomKies** October 27, 2023</sup>
I know it loads in VSC Gauge will pre-register steps.  

Is there any way to utilize that to get a list of steps outputted to a file?  I'm trying to make a list for my user's benefit.  

Going line by line over the file and pulling out the steps in lines starting with `@step` is easy enough, but I'm having issues getting at the ones inside an array.  

Before I reinvent the wheel, I figured I'd ask if there's a CLI tool I may be overlooking like the one that can out put a full list of specs.  </div>

### PR DESCRIPTION
**Pull request by sriv**
usage: gauge list --steps

fixes #2432 

Signed-off-by: sriv <srikanth.ddit@gmail.com>

### CODE REVIEW

**Comment by Elwis28** [comment]
@sriv is there a plan to finish this? It would be a very good addition to gauge.

**Review by zabil — APPROVED** [review]

**Comment by zabil** [comment]
Tested this as follows and all is good


```
⋊> gauge init js                                                                                                                                                                                                                            
Successfully initialized the project. Run specifications with "npm test" in project root.
⋊> gauge list --steps                                                                                                                                                                        16:26:50
[Steps]
Add task <item>
Add tasks <table>
Clear all tasks
Complete tasks <table>
Must display <message>
Must have <table>
Must not have <table>
Open todo application
View <type> tasks
```

**Comment by chadlwilson** [comment]
Filed at https://github.com/getgauge/gauge/issues/2536 for now.

**Comment by chadlwilson** [comment]
Not sure if the stats can be trusted either but the package in question here (the CLI installer) is https://pypistats.org/packages/getgauge-cli rather than the other one (the python language support)

**Comment by zabil** [comment]
Ah yes you are right. So it's something around like

> Downloads last day: 1
Downloads last week: 64
Downloads last month: 213

I am not sure how to interpret it. But it looks like there is decent usage.

**Pull request merged**
