### PR TITLE
1141 extend list command to filter search by tag

### PR DESCRIPTION
**Pull request by ajoecker**
PR for https://github.com/getgauge/gauge/issues/1141

The idea is to allow the user to filter her search with a given tag. 

The new parameter `taggedWith` is taking a string and would filter the results by presenting only those, that are tagged with the given parameter.

Some examples - given the following spec

```
# A simple spec

## A scenario
tags: tags1, tags2
* Step

## Another scenario
tags: tags3, tags4, tags2
* Step
```
| List Command|Result |Comment |
| ------------- | ------------- |------------- |
| `gauge list --scenarios`  | `A scenario, Another scenario`  | no filtering, behaves as before  |
| `gauge list --scenarios --taggedWith tags3`  | `Another scenario` | Only `Another scenario` is tagged with `tags3`  |
| `gauge list --tags --taggedWith tags1`|`tags1, tags2`|Returns all tags that come together with the given one - the filter itself is returned|
|`gauge list --specs --taggedWith tags2`| |Empty result, as no spec is tagged with `tags2`|

### CODE REVIEW

**Comment by zabil** [comment]
Thanks again for this PR
Filtering scenarios by tags is very useful. However it's best to support tag [expressions](https://docs.gauge.org/latest/execution.html#tagged-execution) in the filter. This PR only support filtering with tags.

Can we chain the `--tags` command `--specs` and `--scenario` instead?

For e.g.
```
$ gauge list --specs --tags tag3
[Scenarios]
Another scenario

$ gauge list --specs --tags !tags3
[Scenarios]
A scenario

$ gauge list --specs --tags "tags3 & tags1"
[Scenarios]
A scenario
Another Scenario
```

I am not sure if there's use of parameters when you only use `--tags` maybe it works for validating the expression for e.g

```
$ gauge list --tags
[Tags]
tags1
tags2
tags3
tags4

$ gauge list --tags !tags1
[Tags]
tags2
tags3
tags4

$ gauge list --tags !tags1 & tags5 #tag5 is not in the list use the result to verify
[Tags]
tags2
tags3
tags4

```

**Comment by ajoecker** [comment]
the idea of the PR was to allow filtering based on tags.

Your solution also filters on tags, only that it allows a more complex filtering.

> Can we chain the --tags command --specs and --scenario instead?
Here I have to say that this would confuse me (personally) about what exactly the command would do.

`gauge list --specs --tags tag3` is in my eyes harder to understand as `gauge list --specs --taggedWith tags3`

`gauge list --tags !tags1` would this mean simply to print all tags, except tags1 or all tags, that are not in combination with tags1 ? 

I agree that the syntax for filtering could be extended, so like `gauge list --specs --taggedWith tags1 && !tags2` or so.

But I am not convinced about the propsal with the chaining

**Comment by zabil** [comment]
> But I am not convinced about the proposal with the chaining

My bad, poor choice of words here. Forget that I mentioned chaining.

1) I meant to rename `--taggedWith` to `--tags` to make it consistent with `gauge run --tags` and general convention of not using past tense in command line options
2) Extending the filtering syntax to support whatever is supported by `gauge run --tags`

**Comment by ajoecker** [comment]
ah ok - we are getting closer to agreement here :)

But isn't this then confusing as the `list` command also has the `--tags` parameter for listing tags ?

So to filter scenarios one would use `gauge list --scenarios --tags tags1` and then for filtering tags `gauge list --tags tags1` ? Or `gauge list --tags --tags tags1` (joke)

Isn't it then that `--tags` has multiple meanings ?

**Comment by zabil** [comment]
> But isn't this then confusing as the list command also has the --tags parameter for listing tags ?
Agreed

However with filtering does `--taggedWith` sound ? for e.g
```
$ gauge list --scenarios --taggedWith !tag1
``` 

Reads as list scenarios tagged with not tagged with tag1

How about we do what `git log` does for
```
$ git log ---stat --author <param>
$ git log --graph --after <param>
$ git log --oneline --before
```

For Gauge

```
$ gauge list --scenarios --tag tag1
$ gauge list --scenarios --tag !tag3
$ gauge list --scenarios --tag tag1 & tag3
$ gauge list --tags --tag tag1 # not sure who'd use this so maybe don't allow this
```

**Comment by ajoecker** [comment]
> Reads as list scenarios tagged with not tagged with tag1

For me this is actually _list scenarios tagged with not tag1_

> gauge list --tags --tag tag1 # not sure who'd use this so maybe don't allow this

but this is exactly the use case from https://github.com/getgauge/gauge/issues/1141 (see https://github.com/getgauge/gauge/issues/1141#issuecomment-411725365)

maybe @olejkavn has some input also here

**Comment by nehashri** [comment]
@ajoecker I also like the idea of `--list` here.
Besides this PR has been stale for quite sometime. Can you please update the issue or close it.

**Comment by ajoecker** [comment]
> @ajoecker I also like the idea of `--list` here.
> Besides this PR has been stale for quite sometime. Can you please update the issue or close it.

sorry - i was on holidays.

what do you mean by `the idea of --list` ? 
I would love to continue with that, but as far as I can see, we have not found a common decision yet, no ?

**Comment by ajoecker** [comment]
ok - my suggestion is to scrap this PR, it is already quite old and a lot of discussion is still going on and put the discussion into #1141 ?

Not sure if this is easy to do and agreed on, but I think it is better to discuss on the issue, then an old PR ;-)

**Pull request closed without merging**
