### PR TITLE
print plugin version

### PR DESCRIPTION
**Pull request by ajoecker**
for #1266

introducing a new variable `Version` in the `InstallationResult` to not misuse the `Info` variable, as this might contain other information.

### CODE REVIEW

**Comment by ajoecker** [comment]
will check failing tests

**Comment by ajoecker** [comment]
@nehashri sorry - unfortunately not. I will probably have time by the end of the week

**Comment by ajoecker** [comment]
sorry for the enormous delay... will start to look at it..

**Comment by ajoecker** [comment]
the question for this solution is I assume to print only the version information if one is actually present

so `Failed to install plugin 'unknown' version .` should actually be `Failed to install plugin 'unknown'., right ?

**Comment by nehashri** [comment]
@ajoecker Yes

**Comment by ajoecker** [comment]
> @ajoecker gauge-proto on master seems to be uptodate. any reason why gauge-proto is changed in this PR?

no - no idea why it got updated - not purpose though

**Comment by nehashri** [comment]
You should be able to do it. In your gauge project, goto the gauge-proto directory and checkout the master branch, pull the latest changes. This should remove the proto changes

**Comment by nehashri** [comment]
@ajoecker I will merge this PR and create another commit to fix the gauge-proto issue.

**Pull request merged**
